# _config.yml
remote_theme: pages-themes/cayman@v0.2.0
title: MovieClub
description: A community for movie enthusiasts.
baseurl: "/movieclub" # If your site is published at https://yourusername.github.io/movieclub
url: "https://m-lair.github.io"


