name: Create Feedback Issues

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *' # Runs daily at 9 AM

jobs:
  create-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Parse Feedback JSON and Create Issues
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const feedback = JSON.parse(fs.readFileSync('./feedback.json', 'utf8')).recentItems;

            feedback.forEach(item => {
              const { comment, firstName, lastName, deviceModel, osVersion, timestamp, buildNumber } = item.value.feedbacks[0];
              github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `Feedback: ${comment.substring(0, 50)}`,
                body: `
                  **Feedback**: ${comment}

                  **Details**:
                  - User: ${firstName} ${lastName}
                  - Device: ${deviceModel}
                  - iOS Version: ${osVersion}
                  - Build: ${buildNumber}
                  - Timestamp: ${timestamp}
                `,
                labels: ['feedback', 'bug']
              });
            });
