name: iOS Firebase Testing Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.app

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Install and Build Functions
        run: |
          cd functions
          npm install
          npm install -g typescript
          tsc
          cd lib
          npm install

      - name: Start Firebase Emulators in Background
        run: |
          firebase emulators:start > firebase.log 2>&1 &
          echo "Waiting for emulators to start..."
          sleep 30

      - name: Decode Google Service Info Plist
        run: |
          echo "Decoding GoogleService-Info.plist..."
          echo "${{ secrets.G_SERVICE_64 }}" | base64 --decode > GoogleService-Info.plist
          
          # Print working directory and file existence for debugging
          pwd
          ls -la GoogleService-Info.plist
          
          # Create copies in potential required locations
          cp GoogleService-Info.plist MovieClub/GoogleService-Info.plist || true
          mkdir -p Build/Products/Debug-iphonesimulator/MovieClub.app
          cp GoogleService-Info.plist Build/Products/Debug-iphonesimulator/MovieClub.app/ || true

      - name: Run Swift Tests
        env:
          FIRESTORE_EMULATOR_HOST: localhost:8080
          FUNCTIONS_EMULATOR_HOST: localhost:5001
          AUTH_EMULATOR_HOST: localhost:9099
        run: |
          # Print directory structure for debugging
          ls -R
          
          xcodebuild test \
            -scheme MovieClub \
            -destination "platform=iOS Simulator,name=iPhone 16 Pro,OS=latest" \
            -enableCodeCoverage YES \
            CODE_SIGNING_ALLOWED=NO \
            -resultBundlePath TestResults

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: TestResults