name: iOS starter workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Decode and write Google plist
        run: |
          echo "Decoding ${G_SERVICE_64}..."
          echo "${{ secrets.G_SERVICE_64 }}" | base64 --decode > ./GoogleService-Info.plist
          echo "Wrote to $(pwd)/GoogleService-Info.plist"

      - name: Verify Google plist
        run: |
            if [ ! -f ./GoogleService-Info.plist ]; then
              echo "GoogleService-Info.plist not found!"
              exit 1
            fi

      - name: Build
        uses: sersoft-gmbh/xcodebuild-action@v3
        with:
          project: MovieClub.xcodeproj
          scheme: MovieClub
          destination: platform=macOS
          action: build

      - name: Test
        uses: sersoft-gmbh/xcodebuild-action@v3
        with:
          project: MovieClub.xcodeproj
          scheme: MovieClub
          destination: platform=macOS
          action: test

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install dependencies
        run: |
          cd functions
          npm install

      - name: Test Firebase Functions
        run: |
          cd functions
          npm test
