name: iOS Firebase Testing Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.app

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Install and Build Functions
        run: |
          cd functions
          npm install
          npm install -g typescript
          tsc
          cd lib
          npm install

      - name: Start Firebase Emulators in Background
        run: |
          firebase emulators:start > firebase.log 2>&1 &
          echo "Waiting for emulators to start..."
          sleep 30  # Give emulators time to start
          echo "Emulators should be ready"

      - name: Decode Google Service Info Plist
        run: |
          echo "Decoding ${G_SERVICE_64}..."
          echo "${{ secrets.G_SERVICE_64 }}" | base64 --decode > GoogleService-Info.plist

      - name: Build iOS app
        run: |
          xcodebuild clean build \
            -scheme MovieClub \
            -destination "platform=iOS Simulator,name=iPhone 16 Pro,OS=latest" \
            CODE_SIGNING_ALLOWED=NO \
            -allowProvisioningUpdates | xcpretty

      - name: Run Swift Tests
        env:
          FIRESTORE_EMULATOR_HOST: localhost:8080
          FUNCTIONS_EMULATOR_HOST: localhost:5001
          AUTH_EMULATOR_HOST: localhost:9099
        run: |
          xcodebuild test \
            -scheme MovieClub \
            -destination "platform=iOS Simulator,name=iPhone 16 Pro,OS=latest" \
            -enableCodeCoverage YES \
            CODE_SIGNING_ALLOWED=NO \
            | xcpretty && exit ${PIPESTATUS[0]}

      - name: Run Function Tests
        working-directory: ./functions
        run: npm test

      - name: Upload Firebase Logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: firebase-logs
          path: firebase.log