name: iOS Firebase Testing Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.app

      - name: Install Firebase Tools
        run: npm install -g firebase-tools --silent

      - name: Install and Build Functions
        run: |
          cd functions
          npm install --silent
          npm install -g typescript --silent
          tsc
          cd lib
          npm install --silent

      - name: Start Firebase Emulators in Background
        run: |
          firebase emulators:start > /dev/null 2>&1 &
          sleep 30

      - name: Build App
        run: xcodebuild build \
          -scheme MovieClub \
          -destination "platform=iOS Simulator,name=iPhone 16 Pro,OS=latest" \
          -quiet \
          CODE_SIGNING_ALLOWED=NO

      - name: Decode Google Service Info Plist
        run: |
          echo "${{ secrets.G_SERVICE_64 }}" | base64 --decode > GoogleService-Info.plist
          cp GoogleService-Info.plist MovieClub/
          find /Users/runner/Library/Developer/Xcode/DerivedData \
            -name "MovieClub.app" -type d -exec cp GoogleService-Info.plist {} \;

      - name: Run Swift Tests
        env:
          FIRESTORE_EMULATOR_HOST: localhost:8080
          FUNCTIONS_EMULATOR_HOST: localhost:5001
          AUTH_EMULATOR_HOST: localhost:9099
        run: |
          xcodebuild test \
            -scheme MovieClub \
            -destination "pl
