name: iOS Firebase Testing Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.app

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Install and Build Functions
        run: |
          cd functions
          npm install
          npm install -g typescript
          tsc
          cd lib
          npm install

      - name: Start Firebase Emulators in Background
        run: |
          firebase emulators:start > firebase.log 2>&1 &
          echo "Waiting for emulators to start..."
          sleep 30

      - name: Decode and Place Google Service Info Plist
        run: |
          # First, decode the plist
          echo "Decoding GoogleService-Info.plist..."
          echo "${{ secrets.G_SERVICE_64 }}" | base64 --decode > MovieClub/GoogleService-Info.plist
          
          # Print working directory and verification
          echo "Current directory structure:"
          pwd
          ls -la MovieClub/GoogleService-Info.plist
          echo "Project root contents:"
          ls -la
          echo "MovieClub directory contents:"
          ls -la MovieClub/

      - name: Run Swift Tests
        env:
          FIRESTORE_EMULATOR_HOST: localhost:8080
          FUNCTIONS_EMULATOR_HOST: localhost:5001
          AUTH_EMULATOR_HOST: localhost:9099
        run: |
          # For debugging purposes
          echo "Test execution directory:"
          pwd
          echo "Verifying plist location before tests:"
          ls -la MovieClub/GoogleService-Info.plist
          
          xcodebuild test \
            -scheme MovieClub \
            -destination "platform=iOS Simulator,name=iPhone 16 Pro,OS=latest" \
            -enableCodeCoverage YES \
            CODE_SIGNING_ALLOWED=NO \
            -resultBundlePath TestResults

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: TestResults