name: iOS starter workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Decode and write Google plist
        run: |
          echo "Decoding ${G_SERVICE_64}..."
          echo "${{ secrets.G_SERVICE_64 }}" | base64 --decode > ../GoogleService-Info.plist
          echo "Wrote to $(pwd)/GoogleService-Info.plist"
          
      - name: Build iOS app
        run: |
              xcodebuild clean build -scheme MovieClub -destination -allowProvisioningUpdates "platform=iOS Simulator,name=iPhone 16 Pro,OS=latest"
    
    